### ISSUE TITLE
tests/e2e/test_api_assembly_strategy_combinations_book_then_lang.py::test_en_tn_wa_col_en_tq_wa_col_en_tw_wa_col_sw_tn_col_sw_tq_col_sw_tw_col_sw_tn_tit_sw_tq_tit_sw_tw_tit_book_language_order_1c

### ISSUE THREAD

**Issue by linearcombination** [WycliffeAssociates/DOC#38]
On local (unpushed) branch epub_docx_support_stacked:

```python
[gw0] [  2%] FAILED tests/e2e/test_api_assembly_strategy_combinations_book_then_lang.py::test_en_tn_wa_col_en_tq_wa_col_en_tw_wa_col_sw_tn_col_sw_tq_col_sw_tw_col_sw_tn_tit_sw_tq_tit_sw_tw_tit_book_language_order_1c

================================================================================= FAILURES =================================================================================
______________________ test_en_tn_wa_col_en_tq_wa_col_en_tw_wa_col_sw_tn_col_sw_tq_col_sw_tw_col_sw_tn_tit_sw_tq_tit_sw_tw_tit_book_language_order_1c ______________________
[gw0] darwin -- Python 3.10.1 ~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/.venv/bin/python3

    def test_en_tn_wa_col_en_tq_wa_col_en_tw_wa_col_sw_tn_col_sw_tq_col_sw_tw_col_sw_tn_tit_sw_tq_tit_sw_tw_tit_book_language_order_1c() -> None:
        with TestClient(app=app, base_url=settings.api_test_url()) as client:
            response: requests.Response = client.post(
                "/documents",
                json={
                    "email_address": settings.TO_EMAIL_ADDRESS,
                    "assembly_strategy_kind": model.AssemblyStrategyEnum.BOOK_LANGUAGE_ORDER,
                    "assembly_layout_kind": model.AssemblyLayoutEnum.ONE_COLUMN,
                    "layout_for_print": False,
                    "generate_pdf": True,
                    "generate_epub": False,
                    "generate_docx": False,
                    "resource_requests": [
                        {
                            "lang_code": "en",
                            "resource_type": "tn-wa",
                            "resource_code": "col",
                        },
                        {
                            "lang_code": "en",
                            "resource_type": "tq-wa",
                            "resource_code": "col",
                        },
                        {
                            "lang_code": "en",
                            "resource_type": "tw-wa",
                            "resource_code": "col",
                        },
                        {
                            "lang_code": "sw",
                            "resource_type": "tn",
                            "resource_code": "col",
                        },
                        {
                            "lang_code": "sw",
                            "resource_type": "tq",
                            "resource_code": "col",
                        },
                        {
                            "lang_code": "sw",
                            "resource_type": "tw",
                            "resource_code": "col",
                        },
                        {
                            "lang_code": "sw",
                            "resource_type": "tn",
                            "resource_code": "tit",
                        },
                        {
                            "lang_code": "sw",
                            "resource_type": "tq",
                            "resource_code": "tit",
                        },
                        {
                            "lang_code": "sw",
                            "resource_type": "tw",
                            "resource_code": "tit",
                        },
                    ],
                },
            )
>           check_finished_document_with_body_success(response)

client     = <starlette.testclient.TestClient object at 0x1085b82b0>
response   = <Response [400]>

tests/e2e/test_api_assembly_strategy_combinations_book_then_lang.py:3264:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

response = <Response [400]>

    def check_finished_document_with_body_success(response: requests.Response) -> None:
        """
        Helper to keep tests DRY.

        Check that the finished_document_path exists and also check that
        the HTML file associated with it exists and includes body.
        """
>       assert response.ok
E       assert False
E        +  where False = <Response [400]>.ok

response   = <Response [400]>

tests/e2e/test_api_assembly_strategy_combinations_book_then_lang.py:57: AssertionError
--------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------
2022-06-16 14:16:08,729 DEBUG            asyncio           __init__  59:  Using selector: KqueueSelector
2022-06-16 14:16:08,743 DEBUG document.domain.document_generator               main 654:  document_request: email_address='fake@example.com' assembly_strategy_kind=<AssemblyStrategyEnum.BOOK_LANGUAGE_ORDER: 'blo'> assembly_layout_kind=<AssemblyLayoutEnum.ONE_COLUMN: '1c'> layout_for_print=False resource_requests=[ResourceRequest(lang_code='en', resource_type='tn-wa', resource_code='col'), ResourceRequest(lang_code='en', resource_type='tq-wa', resource_code='col'), ResourceRequest(lang_code='en', resource_type='tw-wa', resource_code='col'), ResourceRequest(lang_code='sw', resource_type='tn', resource_code='col'), ResourceRequest(lang_code='sw', resource_type='tq', resource_code='col'), ResourceRequest(lang_code='sw', resource_type='tw', resource_code='col'), ResourceRequest(lang_code='sw', resource_type='tn', resource_code='tit'), ResourceRequest(lang_code='sw', resource_type='tq', resource_code='tit'), ResourceRequest(lang_code='sw', resource_type='tw', resource_code='tit')] generate_pdf=True generate_epub=False generate_docx=False
2022-06-16 14:16:11,353 DEBUG document.domain.resource_lookup acquire_resource_assets 757:  resource_filepath: working/temp/en_tn-wa/en_tn
2022-06-16 14:16:11,353 DEBUG document.domain.resource_lookup update_resource_dir 862:  resource_dir updated: working/temp/en_tn-wa/en_tn
2022-06-16 14:16:11,354 DEBUG document.domain.resource_lookup acquire_resource_assets 757:  resource_filepath: working/temp/en_tq-wa/en_tq
2022-06-16 14:16:11,355 DEBUG document.domain.resource_lookup update_resource_dir 862:  resource_dir updated: working/temp/en_tq-wa/en_tq
2022-06-16 14:16:11,355 DEBUG document.domain.resource_lookup acquire_resource_assets 757:  resource_filepath: working/temp/en_tw-wa/en_tw
2022-06-16 14:16:11,355 DEBUG document.domain.resource_lookup update_resource_dir 862:  resource_dir updated: working/temp/en_tw-wa/en_tw
2022-06-16 14:16:11,355 DEBUG document.domain.resource_lookup acquire_resource_assets 757:  resource_filepath: working/temp/sw_tn/source.zip
2022-06-16 14:16:11,356 DEBUG document.domain.resource_lookup update_resource_dir 862:  resource_dir updated: working/temp/sw_tn/sw_tn
2022-06-16 14:16:11,356 DEBUG document.domain.resource_lookup acquire_resource_assets 757:  resource_filepath: working/temp/sw_tq/source.zip
2022-06-16 14:16:11,356 DEBUG document.domain.resource_lookup update_resource_dir 862:  resource_dir updated: working/temp/sw_tq/sw_tq
2022-06-16 14:16:11,357 DEBUG document.domain.resource_lookup acquire_resource_assets 757:  resource_filepath: working/temp/sw_tw/source.zip
2022-06-16 14:16:11,357 DEBUG document.domain.resource_lookup update_resource_dir 862:  resource_dir updated: working/temp/sw_tw/sw_tw
2022-06-16 14:16:11,357 DEBUG document.domain.resource_lookup acquire_resource_assets 757:  resource_filepath: working/temp/sw_tn/source.zip
2022-06-16 14:16:11,357 DEBUG document.domain.resource_lookup update_resource_dir 862:  resource_dir updated: working/temp/sw_tn/sw_tn
2022-06-16 14:16:11,358 DEBUG document.domain.resource_lookup acquire_resource_assets 757:  resource_filepath: working/temp/sw_tq/source.zip
2022-06-16 14:16:11,358 DEBUG document.domain.resource_lookup update_resource_dir 862:  resource_dir updated: working/temp/sw_tq/sw_tq
2022-06-16 14:16:11,358 DEBUG document.domain.resource_lookup acquire_resource_assets 757:  resource_filepath: working/temp/sw_tw/source.zip
2022-06-16 14:16:11,358 DEBUG document.domain.resource_lookup update_resource_dir 862:  resource_dir updated: working/temp/sw_tw/sw_tw
2022-06-16 14:16:11,369 DEBUG document.markdown_extensions.remove_section_preprocessor           __init__  20:  sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
2022-06-16 14:16:11,369 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
2022-06-16 14:16:11,369 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
2022-06-16 14:16:11,379 DEBUG document.markdown_extensions.remove_section_preprocessor           __init__  20:  sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
2022-06-16 14:16:11,379 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
2022-06-16 14:16:11,379 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
2022-06-16 14:16:11,449 DEBUG document.markdown_extensions.remove_section_preprocessor           __init__  20:  sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
2022-06-16 14:16:11,449 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
2022-06-16 14:16:11,449 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
2022-06-16 14:16:13,154 DEBUG document.markdown_extensions.link_transformer_preprocessor transform_tw_markdown_links 170:  TW file for filename_sans_suffix: flood not found for lang_code: en
2022-06-16 14:16:13,307 DEBUG document.markdown_extensions.link_transformer_preprocessor transform_tw_markdown_links 170:  TW file for filename_sans_suffix: flood not found for lang_code: en
2022-06-16 14:16:13,442 DEBUG document.markdown_extensions.link_transformer_preprocessor transform_tw_markdown_links 170:  TW file for filename_sans_suffix: flood not found for lang_code: en
2022-06-16 14:16:13,552 DEBUG document.markdown_extensions.link_transformer_preprocessor transform_tw_markdown_links 170:  TW file for filename_sans_suffix: flood not found for lang_code: en
2022-06-16 14:16:14,934 DEBUG document.markdown_extensions.link_transformer_preprocessor transform_tw_markdown_links 170:  TW file for filename_sans_suffix: rom not found for lang_code: en
2022-06-16 14:16:15,429 DEBUG document.markdown_extensions.remove_section_preprocessor           __init__  20:  sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
2022-06-16 14:16:15,429 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
2022-06-16 14:16:15,430 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
2022-06-16 14:16:15,565 DEBUG document.markdown_extensions.remove_section_preprocessor           __init__  20:  sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
2022-06-16 14:16:15,565 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
2022-06-16 14:16:15,566 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
2022-06-16 14:16:15,642 DEBUG document.markdown_extensions.remove_section_preprocessor           __init__  20:  sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
2022-06-16 14:16:15,643 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
2022-06-16 14:16:15,643 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
2022-06-16 14:16:17,149 DEBUG document.markdown_extensions.remove_section_preprocessor           __init__  20:  sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
2022-06-16 14:16:17,150 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
2022-06-16 14:16:17,150 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
2022-06-16 14:16:17,213 DEBUG document.markdown_extensions.remove_section_preprocessor           __init__  20:  sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
2022-06-16 14:16:17,213 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
2022-06-16 14:16:17,214 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
2022-06-16 14:16:17,247 DEBUG document.markdown_extensions.remove_section_preprocessor           __init__  20:  sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
2022-06-16 14:16:17,248 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
2022-06-16 14:16:17,248 DEBUG           MARKDOWN registerExtensions 126:  Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
2022-06-16 14:16:18,320 DEBUG document.domain.assembly_strategies assemble_content_by_book_then_lang 2645:  assembly_layout_for_book_then_lang_strategy: <function assemble_tn_as_iterator_for_book_then_lang at 0x107b83370>
2022-06-16 14:16:18,321 ERROR document.entrypoints.app  document_endpoint  79:  There was an error while attempting to fulfill the document request. Likely reason is the following exception:
Traceback (most recent call last):
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/entrypoints/app.py", line 77, in document_endpoint
    document_request_key = document_generator.main(document_request)
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/document_generator.py", line 732, in main
    content = assemble_content(
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/document_generator.py", line 213, in assemble_content
    content = "".join(
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/assembly_strategies.py", line 2652, in assemble_content_by_book_then_lang
    yield from assembly_layout_for_book_then_lang_strategy(
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/assembly_strategies.py", line 4960, in assemble_tn_as_iterator_for_book_then_lang
    tn_with_most_verses = max(
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/assembly_strategies.py", line 4962, in <lambda>
    key=lambda tn_book_content_unit: tn_book_content_unit.chapters[
KeyError: 1
---------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------
DEBUG    asyncio:selector_events.py:59 Using selector: KqueueSelector
DEBUG    document.domain.document_generator:document_generator.py:654 document_request: email_address='fake@example.com' assembly_strategy_kind=<AssemblyStrategyEnum.BOOK_LANGUAGE_ORDER: 'blo'> assembly_layout_kind=<AssemblyLayoutEnum.ONE_COLUMN: '1c'> layout_for_print=False resource_requests=[ResourceRequest(lang_code='en', resource_type='tn-wa', resource_code='col'), ResourceRequest(lang_code='en', resource_type='tq-wa', resource_code='col'), ResourceRequest(lang_code='en', resource_type='tw-wa', resource_code='col'), ResourceRequest(lang_code='sw', resource_type='tn', resource_code='col'), ResourceRequest(lang_code='sw', resource_type='tq', resource_code='col'), ResourceRequest(lang_code='sw', resource_type='tw', resource_code='col'), ResourceRequest(lang_code='sw', resource_type='tn', resource_code='tit'), ResourceRequest(lang_code='sw', resource_type='tq', resource_code='tit'), ResourceRequest(lang_code='sw', resource_type='tw', resource_code='tit')] generate_pdf=True generate_epub=False generate_docx=False
DEBUG    document.domain.resource_lookup:resource_lookup.py:757 resource_filepath: working/temp/en_tn-wa/en_tn
DEBUG    document.domain.resource_lookup:resource_lookup.py:862 resource_dir updated: working/temp/en_tn-wa/en_tn
DEBUG    document.domain.resource_lookup:resource_lookup.py:757 resource_filepath: working/temp/en_tq-wa/en_tq
DEBUG    document.domain.resource_lookup:resource_lookup.py:862 resource_dir updated: working/temp/en_tq-wa/en_tq
DEBUG    document.domain.resource_lookup:resource_lookup.py:757 resource_filepath: working/temp/en_tw-wa/en_tw
DEBUG    document.domain.resource_lookup:resource_lookup.py:862 resource_dir updated: working/temp/en_tw-wa/en_tw
DEBUG    document.domain.resource_lookup:resource_lookup.py:757 resource_filepath: working/temp/sw_tn/source.zip
DEBUG    document.domain.resource_lookup:resource_lookup.py:862 resource_dir updated: working/temp/sw_tn/sw_tn
DEBUG    document.domain.resource_lookup:resource_lookup.py:757 resource_filepath: working/temp/sw_tq/source.zip
DEBUG    document.domain.resource_lookup:resource_lookup.py:862 resource_dir updated: working/temp/sw_tq/sw_tq
DEBUG    document.domain.resource_lookup:resource_lookup.py:757 resource_filepath: working/temp/sw_tw/source.zip
DEBUG    document.domain.resource_lookup:resource_lookup.py:862 resource_dir updated: working/temp/sw_tw/sw_tw
DEBUG    document.domain.resource_lookup:resource_lookup.py:757 resource_filepath: working/temp/sw_tn/source.zip
DEBUG    document.domain.resource_lookup:resource_lookup.py:862 resource_dir updated: working/temp/sw_tn/sw_tn
DEBUG    document.domain.resource_lookup:resource_lookup.py:757 resource_filepath: working/temp/sw_tq/source.zip
DEBUG    document.domain.resource_lookup:resource_lookup.py:862 resource_dir updated: working/temp/sw_tq/sw_tq
DEBUG    document.domain.resource_lookup:resource_lookup.py:757 resource_filepath: working/temp/sw_tw/source.zip
DEBUG    document.domain.resource_lookup:resource_lookup.py:862 resource_dir updated: working/temp/sw_tw/sw_tw
DEBUG    document.markdown_extensions.remove_section_preprocessor:remove_section_preprocessor.py:20 sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
DEBUG    document.markdown_extensions.remove_section_preprocessor:remove_section_preprocessor.py:20 sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
DEBUG    document.markdown_extensions.remove_section_preprocessor:remove_section_preprocessor.py:20 sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
DEBUG    document.markdown_extensions.link_transformer_preprocessor:link_transformer_preprocessor.py:170 TW file for filename_sans_suffix: flood not found for lang_code: en
DEBUG    document.markdown_extensions.link_transformer_preprocessor:link_transformer_preprocessor.py:170 TW file for filename_sans_suffix: flood not found for lang_code: en
DEBUG    document.markdown_extensions.link_transformer_preprocessor:link_transformer_preprocessor.py:170 TW file for filename_sans_suffix: flood not found for lang_code: en
DEBUG    document.markdown_extensions.link_transformer_preprocessor:link_transformer_preprocessor.py:170 TW file for filename_sans_suffix: flood not found for lang_code: en
DEBUG    document.markdown_extensions.link_transformer_preprocessor:link_transformer_preprocessor.py:170 TW file for filename_sans_suffix: rom not found for lang_code: en
DEBUG    document.markdown_extensions.remove_section_preprocessor:remove_section_preprocessor.py:20 sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
DEBUG    document.markdown_extensions.remove_section_preprocessor:remove_section_preprocessor.py:20 sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
DEBUG    document.markdown_extensions.remove_section_preprocessor:remove_section_preprocessor.py:20 sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
DEBUG    document.markdown_extensions.remove_section_preprocessor:remove_section_preprocessor.py:20 sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
DEBUG    document.markdown_extensions.remove_section_preprocessor:remove_section_preprocessor.py:20 sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
DEBUG    document.markdown_extensions.remove_section_preprocessor:remove_section_preprocessor.py:20 sections_to_remove: ['Examples from the Bible stories', 'Links', 'Picture of', 'Pictures']
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.remove_section_preprocessor.RemoveSectionExtension".
DEBUG    MARKDOWN:core.py:126 Successfully loaded extension "document.markdown_extensions.link_transformer_preprocessor.LinkTransformerExtension".
DEBUG    document.domain.assembly_strategies:assembly_strategies.py:2645 assembly_layout_for_book_then_lang_strategy: <function assemble_tn_as_iterator_for_book_then_lang at 0x107b83370>
ERROR    document.entrypoints.app:app.py:79 There was an error while attempting to fulfill the document request. Likely reason is the following exception:
Traceback (most recent call last):
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/entrypoints/app.py", line 77, in document_endpoint
    document_request_key = document_generator.main(document_request)
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/document_generator.py", line 732, in main
    content = assemble_content(
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/document_generator.py", line 213, in assemble_content
    content = "".join(
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/assembly_strategies.py", line 2652, in assemble_content_by_book_then_lang
    yield from assembly_layout_for_book_then_lang_strategy(
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/assembly_strategies.py", line 4960, in assemble_tn_as_iterator_for_book_then_lang
    tn_with_most_verses = max(
  File "~/src/WA/github.com/linearcombination/DOC_epub_docx_worktree/backend/document/domain/assembly_strategies.py", line 4962, in <lambda>
    key=lambda tn_book_content_unit: tn_book_content_unit.chapters[
KeyError: 1
========================================================================= short test summary info ==========================================================================
FAILED tests/e2e/test_api_assembly_strategy_combinations_book_then_lang.py::test_en_tn_wa_col_en_tq_wa_col_en_tw_wa_col_sw_tn_col_sw_tq_col_sw_tw_col_sw_tn_tit_sw_tq_tit_sw_tw_tit_book_language_order_1c
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! xdist.dsession.Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 1 failed, 9 passed in 21.82s =======================================================================
make: *** [local-e2e-tests] Error 2

```

The issue is likely that we are making an assumption that each language will have the same resources. That is my first guess anyway at the issue.

**Comment by linearcombination** [comment]
Blowing away working/temp and then running tests again made this error go away. I want to try running it twice in a row though to see if it is an issue with GitPython attempting to clone an already existing repo in working/temp/ and erring out. Need to compare same with git cli, i.e., USE_GIT_CLI=true.
